### ISSUE TITLE
Cant load

### ISSUE THREAD

**Issue by HydraBucket** [xiaoxiaodesha/hd_node#2]
HI. Im recieving an error where i cannot import this node. 

Restarting... [Legacy Mode]

## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-07 14:11:04.925641
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\venv\Scripts\python.exe
** Log path: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\rgthree-comfy
   0.1 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 65244 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints E:\AI_Advantage\Data\Models\StableDiffusion
Adding extra search path vae E:\AI_Advantage\Data\Models\VAE
Adding extra search path loras E:\AI_Advantage\Data\Models\Lora
Adding extra search path loras E:\AI_Advantage\Data\Models\LyCORIS
Adding extra search path upscale_models E:\AI_Advantage\Data\Models\ESRGAN
Adding extra search path upscale_models E:\AI_Advantage\Data\Models\RealESRGAN
Adding extra search path upscale_models E:\AI_Advantage\Data\Models\SwinIR
Adding extra search path embeddings E:\AI_Advantage\Data\Models\TextualInversion
Adding extra search path hypernetworks E:\AI_Advantage\Data\Models\Hypernetwork
Adding extra search path controlnet E:\AI_Advantage\Data\Models\ControlNet
Adding extra search path controlnet E:\AI_Advantage\Data\Models\T2IAdapter
Adding extra search path clip E:\AI_Advantage\Data\Models\CLIP
Adding extra search path clip_vision E:\AI_Advantage\Data\Models\InvokeClipVision
Adding extra search path diffusers E:\AI_Advantage\Data\Models\Diffusers
Adding extra search path gligen E:\AI_Advantage\Data\Models\GLIGEN
Adding extra search path vae_approx E:\AI_Advantage\Data\Models\ApproxVAE
Adding extra search path ipadapter E:\AI_Advantage\Data\Models\IpAdapter
Adding extra search path ipadapter E:\AI_Advantage\Data\Models\InvokeIpAdapters15
Adding extra search path ipadapter E:\AI_Advantage\Data\Models\InvokeIpAdaptersXl
Adding extra search path prompt_expansion E:\AI_Advantage\Data\Models\PromptExpansion
Error:
[WinError 1314] A required privilege is not held by the client: 'E:\\AI_Advantage\\Data\\Packages\\VirtualTalentAgencyMain\\custom_nodes\\ComfyLiterals\\js' -> 'E:\\AI_Advantage\\Data\\Packages\\VirtualTalentAgencyMain\\web\\extensions\\ComfyLiterals'
Failed to create symlink to E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyLiterals\js
Target: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\web\extensions\ComfyLiterals
Adding E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\efficiency-nodes-comfyui

Full error log from comfyui_controlnet_aux: 
Traceback (most recent call last):
  File "E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\comfyui_controlnet_aux\__init__.py", line 32, in load_nodes
    module = importlib.import_module(
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'comfyui_controlnet_aux.node_wrappers.desktop'

Loaded ControlNetPreprocessors nodes from E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### Loading: ComfyUI-Impact-Pack (V5.3.1)
Loaded ImpactPack nodes from E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Pack (V5.3.1)
[Impact Pack] Wildcards loading done.
[inference_core_nodes.controlnet_preprocessors] | INFO -> Using ckpts path: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-Inference-Core-Nodes\src\inference_core_nodes\controlnet_preprocessors\ckpts
[inference_core_nodes.controlnet_preprocessors] | INFO -> Using symlinks: False
[inference_core_nodes.controlnet_preprocessors] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']

Full error log from comfyui_controlnet_aux: 
Traceback (most recent call last):
  File "E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-Inference-Core-Nodes\src\inference_core_nodes\controlnet_preprocessors\__init__.py", line 32, in load_nodes
    module = importlib.import_module(
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'inference_core_nodes.controlnet_preprocessors.node_wrappers.desktop'

[inference_core_nodes.controlnet_preprocessors] | INFO -> Some nodes failed to load:
	Failed to import module desktop because ModuleNotFoundError: No module named 'inference_core_nodes.controlnet_preprocessors.node_wrappers.desktop'

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)
### ComfyUI Revision: 2157 [89d0e9ab] | Released on '2024-05-02'
Workspace manager - Openning file hash dict
### Loading: Workspace Manager (V1.0.0)

From Bmad Custom Nodes
 Loaded 122 nodes:
  + api nodes (14)
  + simple utility nodes (58)
  + CV nodes (49)
  + color clip ade20k node (1)
 Not loaded:
  * extension dependent nodes
 Problems:
  ! No module named 'custom_nodes.ComfyUI_ADV_CLIP_emb'

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------

Full error log from comfyui_controlnet_aux: 
Traceback (most recent call last):
  File "E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\comfyui_controlnet_aux\__init__.py", line 32, in load_nodes
    module = importlib.import_module(
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'comfyui_controlnet_aux.node_wrappers.desktop'

[tinyterraNodes] Loaded
[comfy_mtb] | INFO -> loaded 69 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (6) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Traceback (most recent call last):
  File "E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\hd_node\__init__.py", line 1, in <module>
    from .HDNodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\hd_node\HDNodes.py", line 18, in <module>
    from .reactor_swapper import swap_face, get_current_faces_model, analyze_faces, get_face_single
  File "E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\hd_node\reactor_swapper.py", line 11, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

Cannot import E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\hd_node module for custom nodes: No module named 'insightface'

[rgthree] Loaded 38 fantastic nodes.
[rgthree] Will use rgthree's optimized recursive execution.

Searge-SDXL v4.3.1 in E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\SeargeSDXL
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

	"Art is the breath of life." - Liza Donnelly

Import times for custom nodes:
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\fw_nodes.py
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-Logic
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\extended-saveimage-comfyui
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\cg-use-everywhere
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\save-image-extended-comfyui
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyLiterals
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-TextUtils
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\Comfy_KepListStuff
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\rgthree-comfy
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds (IMPORT FAILED): E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\hd_node
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\comfyui_bmad_nodes
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\comfyui-workspace-manager
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-Inference-Core-Nodes
   0.2 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\comfyui-dynamicprompts
   0.2 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\SeargeSDXL
   0.3 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\ComfyUI-Manager
   0.5 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\comfy_mtb
   0.6 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\comfyui-art-venture
   0.9 seconds: E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
[comfy_mtb] | WARNING -> Found multiple match, we will pick the first E:\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\models\upscale_models
['E:\\AI_Advantage\\Data\\Packages\\VirtualTalentAgencyMain\\models\\upscale_models', 'E:\\AI_Advantage\\Data\\Models\\ESRGAN', 'E:\\AI_Advantage\\Data\\Models\\RealESRGAN', 'E:\\AI_Advantage\\Data\\Models\\SwinIR']
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

**Comment by xiaoxiaodesha** [comment]
E：\AI_Advantage\Data\Packages\VirtualTalentAgencyMain\custom_nodes\hd_node
你并没有导入成功我的代码

**Comment by xiaoxiaodesha** [comment]
insightface安装先安装Visual Studio并安装c++桌面开发以及通用的win通用平台生成工具

**Comment by HydraBucket** [comment]
Thank you for getting back to me. I have Visual Studio and all c++ dependencies downloaded. I had them prior to my issue - have I imported them incorrectly?

**Comment by xiaoxiaodesha** [comment]
确保comfyui和你的 Visual Studio 和所有 c++ 依赖项是同一个环境，可以了解一下python 虚拟环境这个概念

**Comment by xiaoxiaodesha** [comment]
comfyui终端会告诉你是否成功的

**Comment by xiaoxiaodesha** [comment]
![1715233774734](https://github.com/xiaoxiaodesha/hd_node/assets/20954135/749a77ba-9647-4300-a548-335586ed139e

**Comment by xiaoxiaodesha** [comment]
继续看你的终端错误，仔细找找问题是什么？
你安装我的节点，主要是为了解决那一部分问题

**Comment by xghgj0508** [comment]
安装自定义节点“hd-nodes-comfyui”已完成但不起作用

**Comment by xiaoxiaodesha** [comment]
你需要什么作用
